### ISSUE TITLE
[Question] Number of active THB-splines on any given cell.

### ISSUE THREAD

**Issue by qTipTip** [rafavzqz/geopdes#4]
Hi! It's me again!

Thanks for your previous help.

I am wondering whether it is possible to get the number of active truncated hierarchical B-splines on each cell in a hierarchical mesh? I haven't been able to extract this information from the data structures.

Is there any clear cut way of doing this, or do you happen to have any ideas on how I might go about getting these numbers? 

Best regards,
Ivar

**Comment by rafavzqz** [comment]
Hi Ivar!

That information is not stored in the structure, but you can easily retrieve with the help of Csub, that writes the THB-splines as linear combination of B-splines of a given level. Since you know the B-splines that do not vanish on the element, it is then easy to get the THB-splines. For instance, for the kth element of level lev

elem = hmsh.active{lev}(k)
indices = sp_get_basis_functions (hspace_space_of_level(lev), hmsh.mesh_of_level(lev), elem);
[~,jj] = find (hspace.Csub{lev}(indices,:));
functions_on_the_element = unique (jj);
number_of_functions = numel (unique (jj));

You can put this into two loops (levels and elements), if you want to compute it for all elements.

Best,
Rafa

**Comment by qTipTip** [comment]
Thanks again!

That seemed to do the trick - I was not sure how to extract this information. Cheers!

Best regards, 
Ivar
