### ISSUE TITLE
hierarchical control points

### ISSUE THREAD

**Issue by hamidratri** [rafavzqz/geopdes#8]
Dear Rafa
I appreciate the time you spend guiding me.
I am writing to ask if you could help me with how I can translate control points between different hierarchical levels?
suppose I have control points of level one, how can I calculate the control points of (T)HB space?
I have written the following code to calculate all control points of each level, is there any way to directly calculate the control points of each element separately?

%%
coeff_lev   = cell(size(hmsh.nel_per_level));
CntrlPts     = cell(size(hspace.space_of_level));
% Control points of first level
CntrlPts{1} = geometry.nurbs.coefs;
% Control points of other levels using subdivision matrix
for i = 1:numel(hspace.Proj)
    CntrlPts{i+1} = CntrlPts{i}*hspace.Proj{i}';
end
for ilev = 1:numel(hspace.space_of_level)  
    [~,jj]=find(hspace.Csub{ilev}(hspace.active{ilev},:));
    coeff_lev{ilev} = CntrlPts{ilev}(:,hspace.active{ilev})*hspace.Csub{ilev}(hspace.active{ilev},jj);
end

Best Regards
Hamid

**Comment by rafavzqz** [comment]
Dear Hamid,
the matrix refinement between two consecutive levels, for tensor-product B-splines, can be computed using the function matrix_basis_change__. Note that the field hspace.Proj only contains the 1D subdivision matrices, and the function computes the Kronecker tensor product of those matrices.

To pass from level one to (T)HB-splines, you can use the matrix Cref, computed as the output of hspace_refine. If you apply several refinement steps, you will need to use the product of several of these matrices.

To compute the control points of each element separately you would need to work with local matrices, and use a local version of Cref. In principle there is no problem to do it, but I don't know if this will be convenient in Matlab. Since the same function (or control point) appears in many elements, you will repeat the same computation several times.

I hope that was helpful.
Best regards,
Rafa
